# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('DB', 'Debit'), ('CR', 'Credit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(related_name='transaction', to='expense_collector.Tag')),
            ],
            options={
                'ordering': ('name', 'type', 'amount', 'description'),
            },
        ),
        migrations.CreateModel(
            name='TransactionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('transaction_set_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(related_name='transaction_set', to='expense_collector.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_collector.TransactionSet'),
        ),
    ]
