# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('transactions', models.ManyToManyField(to='expense_collector.Transaction')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
