# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='transaction_sets',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(related_name='transaction', to='expense_collector.Tag'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='expense_collector.TransactionSet'),
        ),
        migrations.AddField(
            model_name='transactionset',
            name='tags',
            field=models.ManyToManyField(related_name='transaction_set', to='expense_collector.Tag'),
        ),
    ]
