# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_collector', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DB', 'Debit'), ('CR', 'Credit')], max_length=2),
        ),
    ]
