# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_collector', '0002_auto_20171114_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_collector.TransactionSet'),
        ),
    ]
