# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_collector', '0003_auto_20171115_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('name', 'type', 'amount', 'description')},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='price',
            new_name='amount',
        ),
    ]
